# Accept a build argument for the base image
ARG BASE_IMAGE

# Pull base image
FROM ${BASE_IMAGE}

USER root
# Install wget
RUN apt-get update && apt-get install -y wget

# Include the health check
HEALTHCHECK --interval=30s --timeout=3s \
  CMD wget --quiet --tries=1 --spider -qO- http://localhost:8080/actuator/health | grep UP || exit 1
